import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { SESSION_COOKIE_NAME } from "@/lib/constant";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={poppins.className} >{children}</body>
    </html>
  );
}
